routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => 'auth'], function () {
    Route::get('/', 'HomeController@index')->name('home');

    /**
     * Rutas Para notificaciones
     */
    Route::post('notifications', 'NotificationController@store');
    Route::get('notifications', 'NotificationController@index');
    Route::patch('notifications/{id}/read', 'NotificationController@markAsRead');
    Route::post('notifications/mark-all-read', 'NotificationController@markAllRead');

    /**
     * Rutas de perfil
     */
    Route::get('profile', 'ProfileController@edit')->name('profile.edit');
    Route::put('profile', 'ProfileController@update')->name('profile.update');
    Route::put('profile/password', 'ProfileController@password')->name('profile.password');

    //Todo con prefino asistencias va al controller de asistencias donde todo termina renderizado mediante vue
    Route::get('/asistencias/{any?}', 'Asistencia\AsistenciaController@index')->where('any', '.*');

    /* Route::get('asistencias/{id}','Asistencia\AsistenciaController@index');*/
    /**
     * Mantenedores
     */
    Route::group(['prefix' => 'mantenedores'], function () {
        /**
         * Solo user y roles usan interfaz echa con blade.
         */
        Route::resource('roles', 'RoleController');
        Route::resource('user', 'UserController', ['except' => ['show']]);
        Route::get('/{any?}', 'MantenedoresController@index')->where('any', '.*');
    });

});



/*Route::post('notifications/{id}/dismiss', 'NotificationController@dismiss');*/

resources/views/layouts/navbars/navbar.blade.php
@auth()
    @include('layouts.navbars.navs.auth')
@endauth

resources/views/layouts/navbars/sidebar.blade.php
<nav class="navbar navbar-vertical fixed-left navbar-expand-md navbar-dark bg-gradient-dark sidebar" id="sidenav-main">
    <div class="container-fluid">
        <!-- Toggler -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#sidenav-collapse-main"
                aria-controls="sidenav-main" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <!-- Brand -->

        <a class="navbar-brand pt-0" href="{{ route('home') }}" id="brand">
            <img src="{{asset('images/logo_GEA_Chile.png')}}" alt="..." style="max-width: 100%; max-height: 4rem;">
        </a>

        <!-- User -->
        <ul class="nav align-items-center d-md-none">
            <li class="nav-item dropdown">
                <a class="nav-link" href="#" role="button" data-toggle="dropdown" aria-haspopup="true"
                   aria-expanded="false">
                    <div class="media align-items-center">
                        <span class="avatar avatar-sm rounded-circle">
                        <img alt="Image placeholder" src="{{ asset('argon') }}/img/theme/team-1-800x800.jpg">
                        </span>
                    </div>
                </a>
                <div class="dropdown-menu dropdown-menu-arrow dropdown-menu-right">
                    <div class=" dropdown-header noti-title">
                        <h6 class="text-overflow m-0">{{ __('Welcome!') }}</h6>
                    </div>
                    <a href="{{ route('profile.edit') }}" class="dropdown-item">
                        <i class="ni ni-single-02"></i>
                        <span>{{ __('My profile') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-settings-gear-65"></i>
                        <span>{{ __('Settings') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-calendar-grid-58"></i>
                        <span>{{ __('Activity') }}</span>
                    </a>
                    <a href="#" class="dropdown-item">
                        <i class="ni ni-support-16"></i>
                        <span>{{ __('Support') }}</span>
                    </a>
                    <div class="dropdown-divider"></div>
                    <a href="{{ route('logout') }}" class="dropdown-item" onclick="event.preventDefault();
                    document.getElementById('logout-form').submit();">
                        <i class="ni ni-user-run"></i>
                        <span>{{ __('Logout') }}</span>
                    </a>
                </div>
            </li>
        </ul>
        <!-- Collapse -->
        <div class="collapse navbar-collapse" id="sidenav-collapse-main">
            <!-- Collapse header -->
            <div class="navbar-collapse-header d-md-none">
                <div class="row">
                    <div class="col-6 collapse-brand">
                        <a href="{{ route('home') }}">
                            <img src="{{asset('images/logo_GEA_Chile.png')}}">
                        </a>
                    </div>
                    <div class="col-6 collapse-close">
                        <button type="button" class="navbar-toggler" data-toggle="collapse"
                                data-target="#sidenav-collapse-main" aria-controls="sidenav-main" aria-expanded="false"
                                aria-label="Toggle sidenav">
                            <span></span>
                            <span></span>
                        </button>
                    </div>
                </div>
            </div>
            <!-- Navigation -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('home') }}">
                        <i class="ni ni-tv-2 text-primary"></i> {{ __('Dashboard') }}
                    </a>
                </li>
                @can('cirugia-list')
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url('asistencias')}}">
                            <i class="ni ni-archive-2"></i>
                            <span class="nav-link-text">Cirugias</span>
                        </a>
                    </li>
                @endcan
                <li class="nav-item">
                    <a class="nav-link" href="{{ route('profile.edit') }}">
                        <i class="ni ni-single-02"></i>
                        <span class="nav-link-text">Perfil</span>
                    </a>
                </li>
                @can('mantenedores-list')
                    <li class="nav-item">
                        <a class="nav-link" href="#navbar-examples" data-toggle="collapse" role="button"
                           aria-expanded="true" aria-controls="navbar-examples">
                            <i class="ni ni-settings"></i>
                            <span class="nav-link-text">Configuración</span>
                        </a>

                        <div class="collapse" id="navbar-examples">

                            <ul class="nav nav-sm flex-column">
                                @can('user-list')
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('user.index') }}">
                                            <i class="fas fa-user-cog"></i>
                                            Usuarios
                                        </a>
                                    </li>
                                @endcan
                                @can('bonos-list')
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url('mantenedores/bonos') }}">
                                            <i class="fas fa-list"></i>
                                            Bonos
                                        </a>
                                    </li>
                                @endcan
                                @can('role-list')
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ route('roles.index') }}">
                                            <i class="fas fa-circle-notch"></i>
                                            Roles
                                        </a>
                                    </li>
                                @endcan
                                @can('previsiones-list')
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url('mantenedores/previsiones') }}">
                                            <i class="fas fa-list"></i>
                                            Previsiones
                                        </a>
                                    </li>
                                @endcan
                                @can('diagnosticos-list')
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url('mantenedores/diagnosticos') }}">
                                            <i class="fas fa-list"></i>
                                            Diagnosticos
                                        </a>
                                    </li>
                                @endcan
                                @can('procedimientos-list')
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url('mantenedores/procedimientos') }}">
                                            <i class="fas fa-list"></i>
                                            Procedimientos
                                        </a>
                                    </li>
                                @endcan
                                @can('regiones-list')
                                    <li class="nav-item">
                                        <a class="nav-link" href="{{ url('mantenedores/regiones') }}">
                                            <i class="fas fa-list"></i>
                                            Regiones
                                        </a>
                                    </li>
                                @endcan
                            </ul>

                        </div>
                    </li>
                @endcan
            </ul>
            <!-- Divider -->
            <hr class="my-3">
            <!-- Heading -->
            <h6 class="navbar-heading text-muted">Documentation</h6>
            <!-- Navigation -->
            <ul class="navbar-nav mb-md-3">
                <li class="nav-item">
                    <a class="nav-link"
                       href="https://demos.creative-tim.com/argon-dashboard/docs/getting-started/overview.html">
                        <i class="ni ni-spaceship"></i> Getting started
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="https://demos.creative-tim.com/argon-dashboard/docs/foundation/colors.html">
                        <i class="ni ni-palette"></i> Foundation
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link"
                       href="https://demos.creative-tim.com/argon-dashboard/docs/components/alerts.html">
                        <i class="ni ni-ui-04"></i> Components
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>